[project]
name = "check60"
version = "1.0.0"
description = "Utility for fast check your programs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "pyinstaller>=6.17.0",
    "pyyaml>=6.0.3",
]
